/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AchievementsTimeline: typeof import('./src/components/portal/AchievementsTimeline.vue')['default']
    ArticlesSection: typeof import('./src/components/portal/ArticlesSection.vue')['default']
    ClickRipple: typeof import('./src/components/effects/ClickRipple.vue')['default']
    CourseSchedule: typeof import('./src/components/portal/CourseSchedule.vue')['default']
    CustomCards: typeof import('./src/components/portal/CustomCards.vue')['default']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    IdentityCards: typeof import('./src/components/portal/IdentityCards.vue')['default']
    MomentsFeed: typeof import('./src/components/portal/MomentsFeed.vue')['default']
    PageTransition: typeof import('./src/components/effects/PageTransition.vue')['default']
    ParticleCanvas: typeof import('./src/components/effects/ParticleCanvas.vue')['default']
    PhotoWall: typeof import('./src/components/portal/PhotoWall.vue')['default']
    PortalBackground: typeof import('./src/components/portal/PortalBackground.vue')['default']
    PortalNavbar: typeof import('./src/components/portal/PortalNavbar.vue')['default']
    PortalSettings: typeof import('./src/components/portal/PortalSettings.vue')['default']
    ProfileCard: typeof import('./src/components/portal/ProfileCard.vue')['default']
    ProjectShowcase: typeof import('./src/components/portal/ProjectShowcase.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchoolQuickLinks: typeof import('./src/components/portal/SchoolQuickLinks.vue')['default']
    SchoolStats: typeof import('./src/components/portal/SchoolStats.vue')['default']
    SettingsAchievementEditor: typeof import('./src/components/portal/SettingsAchievementEditor.vue')['default']
    SettingsAppearance: typeof import('./src/components/portal/SettingsAppearance.vue')['default']
    SettingsArticleEditor: typeof import('./src/components/portal/SettingsArticleEditor.vue')['default']
    SettingsMomentEditor: typeof import('./src/components/portal/SettingsMomentEditor.vue')['default']
    SettingsPhotoEditor: typeof import('./src/components/portal/SettingsPhotoEditor.vue')['default']
    SettingsScheduleEditor: typeof import('./src/components/portal/SettingsScheduleEditor.vue')['default']
    SiteDashboard: typeof import('./src/components/portal/SiteDashboard.vue')['default']
    SkillsRadar: typeof import('./src/components/portal/SkillsRadar.vue')['default']
    SocialButton: typeof import('./src/components/portal/SocialButton.vue')['default']
    SteamHub: typeof import('./src/components/portal/SteamHub.vue')['default']
    ToastContainer: typeof import('./src/components/effects/ToastContainer.vue')['default']
  }
}
